name: Check quality of code and test code

on: push

jobs:
  build:
    name: CHeck code quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user

  check:
    name: Run code analysis
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - name: Ruff
      run: ruff check src